import Link from "next/link";

const CONTACT_EMAIL = "admin@er-democracy-bologna.xyz";

const PRIVACY_SECTIONS = [
  {
    title: "1. Introduction",
    body: [
      "This Privacy Policy explains how ER Democracy Bologna processes personal data when you access the platform, create an account, participate in consultations, submit content, use account-recovery features, or contact the platform.",
      "Personal data is processed lawfully, fairly, transparently, and only for purposes connected with operating, securing, improving, and administering the platform.",
    ],
  },
  {
    title: "2. Controller and contact",
    body: [
      "ER Democracy Bologna is the platform responsible for the processing described in this Privacy Policy, unless another controller is clearly identified for a specific activity.",
      `For privacy questions, data-rights requests, or concerns about personal data, contact ${CONTACT_EMAIL}.`,
    ],
  },
  {
    title: "3. Data we may process",
    body: [
      "Account data: full name, email address, account status, role, email-verification status, and records showing acceptance of applicable terms.",
      "Authentication and security data: information needed to verify accounts, manage sessions, reset passwords, protect access, prevent misuse, and maintain platform security.",
      "Participation data: consultation choices, voting or assessment inputs, submitted proposals, comments, forms, and related participation records where those features are used.",
      "Public-content data: articles, consultation information, published updates, and content submitted or managed through authorized platform functions.",
      "Technical data: IP address, device or browser information, timestamps, request metadata, and logs needed for security, troubleshooting, auditability, and service reliability.",
      "Contact data: information you provide when contacting the platform, including your email address, message content, and any context needed to respond to your request.",
    ],
  },
  {
    title: "4. How data is collected",
    body: [
      "Data may be collected directly from you when you create an account, sign in, verify your email, request a password reset, participate in consultations, submit content, or contact the platform.",
      "Some technical and security data may be collected automatically when you access or use the platform.",
      "Some information may be generated by the platform as part of normal account, participation, security, or administrative activity.",
    ],
  },
  {
    title: "5. Why data is processed",
    body: [
      "To create and manage accounts, authenticate users, verify email addresses, process password-reset requests, and provide secure access to account-based features.",
      "To publish and manage consultations, record participation, apply consultation rules, calculate results, and display participation outputs where enabled.",
      "To receive, review, moderate, and manage proposals, comments, forms, or other submissions.",
      "To operate, maintain, secure, test, troubleshoot, and improve the platform.",
      "To prevent fraud, misuse, unauthorized access, manipulation of voting or participation, and activity that could harm users or platform integrity.",
      "To respond to support, privacy, legal, or administrative requests.",
      "To comply with legal obligations, preserve necessary records, and protect the legitimate interests of the platform and its users.",
    ],
  },
  {
    title: "6. Legal bases",
    body: [
      "Contract or pre-contractual steps may apply where processing is necessary to create an account, provide access, manage authentication, and operate requested platform features.",
      "Legitimate interests may apply where processing is necessary to secure the platform, prevent abuse, maintain records, troubleshoot issues, moderate submissions, and preserve consultation integrity, provided those interests are not overridden by user rights and freedoms.",
      "Legal obligation may apply where processing, retention, or disclosure is required by applicable law or lawful authority.",
      "Consent may apply where the platform requests consent for a specific optional activity, such as non-essential cookies or similar technologies.",
      "Public interest or other lawful bases may apply only where a specific activity has a valid legal basis under applicable law.",
    ],
  },
  {
    title: "7. Consultation and participation visibility",
    body: [
      "Consultation results may be shown publicly, privately, after participation, after closure, or not at all, depending on the settings and purpose of each consultation.",
      "Public results are intended to be aggregated, summarized, or otherwise presented without directly exposing individual personal data unless a specific feature clearly states otherwise.",
      "Authorized administrators may access participation-related records where necessary to operate consultations, review integrity, manage results, provide support, or comply with legal obligations.",
    ],
  },
  {
    title: "8. Submissions and moderation",
    body: [
      "If you submit proposals, comments, messages, forms, or other content, the platform may process that content to receive, review, moderate, display, store, or respond to it.",
      "Submitted content may be restricted, hidden, removed, or retained where needed for moderation, security, consultation integrity, legal compliance, or dispute handling.",
    ],
  },
  {
    title: "9. Email communications",
    body: [
      "The platform may use your email address for essential service communications, including account registration, email verification, password reset, security notices, account-related updates, and responses to your requests.",
      "These operational messages are necessary for account and platform functionality and are separate from optional marketing communications, if any are introduced later.",
    ],
  },
  {
    title: "10. Cookies and similar technologies",
    body: [
      "The platform may use essential cookies or similar technologies needed for authentication, security, session management, cookie preferences, and core platform functionality.",
      "Non-essential cookies or similar technologies, if used, should be handled according to applicable consent requirements and explained in the Cookie Policy.",
      "More information is available in the Cookie Policy.",
    ],
  },
  {
    title: "11. Sharing of personal data",
    body: [
      "Personal data may be processed by service providers that support hosting, infrastructure, database operation, authentication, email delivery, security, maintenance, analytics, or other technical functions necessary for the platform.",
      "Service providers are expected to process personal data only as needed to provide their services and subject to appropriate contractual, technical, and organizational safeguards.",
      "Personal data is not sold. Data may be disclosed where required by law, lawful authority, legal process, security necessity, or to protect rights, users, and platform integrity.",
    ],
  },
  {
    title: "12. International transfers",
    body: [
      "Where personal data is processed outside the European Economic Area or another relevant jurisdiction, appropriate safeguards should be used where required by applicable data protection law.",
      "Such safeguards may include contractual protections, provider security commitments, adequacy decisions, or other lawful transfer mechanisms where applicable.",
    ],
  },
  {
    title: "13. Retention",
    body: [
      "Personal data is retained only for as long as necessary for the purposes described in this Privacy Policy, including account management, consultation records, security, auditability, legal compliance, dispute handling, and platform integrity.",
      "Different retention periods may apply to account data, consultation participation records, submitted content, security logs, contact messages, verification records, and password-reset records.",
      "Where data is no longer needed, it may be deleted, anonymized, aggregated, or retained only where a valid legal or operational reason remains.",
    ],
  },
  {
    title: "14. Security",
    body: [
      "The platform applies technical and organizational measures intended to protect personal data against unauthorized access, loss, misuse, alteration, or disclosure.",
      "Security measures may include access controls, encrypted or protected credentials, session protections, validation checks, role-based permissions, logging, monitoring, and other safeguards appropriate to the platform.",
      "No online platform can guarantee absolute security. Users should keep their login credentials confidential and report suspected unauthorized access promptly.",
    ],
  },
  {
    title: "15. Your rights",
    body: [
      "Subject to applicable law, you may have the right to request access to your personal data, correction of inaccurate data, deletion, restriction of processing, objection to certain processing, and portability of data you provided.",
      "Where processing is based on consent, you may have the right to withdraw consent at any time without affecting processing that occurred before withdrawal.",
      "Some requests may be limited where continued processing is necessary for legal compliance, security, auditability, fraud prevention, consultation integrity, dispute handling, or the establishment, exercise, or defense of legal claims.",
      `To exercise privacy rights, contact ${CONTACT_EMAIL}. Identity verification may be required before action is taken on a request.`,
    ],
  },
  {
    title: "16. Complaints",
    body: [
      "If you believe your personal data has been handled unlawfully or your request has not been handled properly, you may contact the platform first so the issue can be reviewed.",
      "Where applicable, you may also have the right to lodge a complaint with a competent data protection authority.",
    ],
  },
  {
    title: "17. Children and restricted users",
    body: [
      "The platform is not intended for unlawful or unauthorized use by anyone who is not permitted to use it under applicable law.",
      "Where age, capacity, institutional, or legal restrictions apply, users should access the platform only where legally permitted or with appropriate authorization.",
    ],
  },
  {
    title: "18. Changes to this Privacy Policy",
    body: [
      "This Privacy Policy may be updated to reflect legal, technical, operational, or platform changes. The latest version will be published on this page.",
      "Where required by law, additional notice or consent may be requested for material changes.",
    ],
  },
  {
    title: "19. Contact",
    body: [
      `For privacy-related questions, data-rights requests, or concerns, contact ${CONTACT_EMAIL}.`,
    ],
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-white text-slate-900">
      <section className="px-5 py-10 sm:px-6 md:py-14">
        <div className="mx-auto max-w-6xl">
          <div className="h-[2px] w-full bg-gradient-to-r from-green-600 via-white to-red-600" />

          <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,0.62fr)_minmax(0,1fr)] lg:items-start">
            <aside className="min-w-0 lg:sticky lg:top-28">
              <p className="text-xs font-black uppercase tracking-[0.24em] text-slate-500">
                Legal
              </p>

              <h1 className="mt-4 max-w-4xl break-words text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-5xl md:text-6xl">
                Privacy Policy.
              </h1>

              <p className="mt-6 max-w-3xl break-words text-base leading-8 text-slate-600">
                This Privacy Policy explains how ER Democracy Bologna processes
                personal data for accounts, authentication, consultations,
                participation, submissions, security, support, and administration.
              </p>

              <div className="mt-8 border border-slate-200 bg-white p-5 shadow-[0_24px_70px_rgba(15,23,42,0.08)] transition duration-300 hover:-translate-y-1 hover:border-green-200 hover:shadow-[0_34px_90px_rgba(15,23,42,0.12)] active:-translate-y-1 active:scale-[0.99] active:border-green-200">
                <p className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">
                  Last updated
                </p>

                <p className="mt-3 text-lg font-black tracking-[-0.03em] text-slate-950">
                  28 June 2026
                </p>

                <p className="mt-4 text-sm leading-7 text-slate-600">
                  Privacy contact:
                </p>

                <a
                  href={`mailto:${CONTACT_EMAIL}`}
                  className="mt-2 block break-words text-sm font-black text-green-700 underline underline-offset-4 transition duration-300 hover:text-green-800 active:text-green-800"
                >
                  {CONTACT_EMAIL}
                </a>
              </div>

              <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:flex-wrap lg:flex-col">
                <SideLink href="/terms">Terms of Service →</SideLink>
                <SideLink href="/cookies">Cookie Policy →</SideLink>
                <SideLink href="/contact">Contact →</SideLink>
              </div>
            </aside>

            <section className="grid min-w-0 gap-5">
              {PRIVACY_SECTIONS.map((section) => (
                <article
                  key={section.title}
                  className="min-w-0 border border-slate-200 bg-white p-5 shadow-[0_18px_54px_rgba(15,23,42,0.06)] transition duration-300 hover:-translate-y-1 hover:border-slate-300 hover:shadow-[0_26px_74px_rgba(15,23,42,0.10)] active:-translate-y-1 active:scale-[0.99]"
                >
                  <h2 className="break-words text-xl font-black tracking-[-0.035em] text-slate-950 sm:text-2xl">
                    {section.title}
                  </h2>

                  <div className="mt-4 grid gap-4">
                    {section.body.map((paragraph) => (
                      <p
                        key={paragraph}
                        className="break-words text-base leading-8 text-slate-700"
                      >
                        {paragraph}
                      </p>
                    ))}
                  </div>
                </article>
              ))}
            </section>
          </div>

          <div className="mt-14 flex flex-col gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:flex-wrap">
            <FooterLink href="/terms">View terms →</FooterLink>
            <FooterLink href="/cookies">View cookie policy →</FooterLink>
            <FooterLink href="/contact">Contact us →</FooterLink>
          </div>
        </div>
      </section>
    </main>
  );
}

function SideLink({ href, children }: { href: string; children: string }) {
  return (
    <Link
      href={href}
      className="inline-flex min-h-11 w-full items-center justify-center border border-slate-300 bg-white px-4 text-sm font-black text-slate-800 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-slate-400 hover:shadow-md active:-translate-y-1 active:scale-[0.98] active:border-slate-400 active:bg-slate-50 sm:w-auto lg:w-full"
    >
      {children}
    </Link>
  );
}

function FooterLink({ href, children }: { href: string; children: string }) {
  return (
    <Link
      href={href}
      className="inline-flex min-h-11 w-full items-center justify-center border border-slate-300 bg-white px-4 text-sm font-black text-slate-800 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-slate-400 hover:shadow-md active:-translate-y-1 active:scale-[0.98] active:border-slate-400 active:bg-slate-50 sm:w-auto"
    >
      {children}
    </Link>
  );
}
