import { PERMISSIONS, type Permission } from './permissions.constants';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.CONSULTATION_EDIT,
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
    PERMISSIONS.PARTICIPANTS_VIEW_ADMIN,
    PERMISSIONS.ASSESSMENT_SECRET_LOOKUP,
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_EDIT,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_PUBLISH,
    PERMISSIONS.ARTICLE_VIEW_ADMIN,
    PERMISSIONS.MEDIA_UPLOAD,
  ],

  CONSULTATION_ADMIN: [
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.CONSULTATION_EDIT,
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
    PERMISSIONS.PARTICIPANTS_VIEW_ADMIN,
  ],

  CONTENT_ADMIN: [
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_EDIT,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_PUBLISH,
    PERMISSIONS.ARTICLE_VIEW_ADMIN,
    PERMISSIONS.MEDIA_UPLOAD,
  ],

  ANALYTICS_ADMIN: [
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
  ],

  AUDITOR: [
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
    PERMISSIONS.PARTICIPANTS_VIEW_ADMIN,
    PERMISSIONS.ASSESSMENT_SECRET_LOOKUP,
  ],

  USER: [],
};

export function roleHasPermission(
  role: string,
  permission: Permission,
): boolean {
  return (ROLE_PERMISSIONS[role] ?? []).includes(permission);
}
