export const PERMISSIONS = {
  CONSULTATION_CREATE: 'CONSULTATION_CREATE',
  CONSULTATION_EDIT: 'CONSULTATION_EDIT',
  CONSULTATION_VIEW_ADMIN: 'CONSULTATION_VIEW_ADMIN',
  RESULTS_VIEW_ADMIN: 'RESULTS_VIEW_ADMIN',
  ANALYTICS_VIEW_ADMIN: 'ANALYTICS_VIEW_ADMIN',
  PARTICIPANTS_VIEW_ADMIN: 'PARTICIPANTS_VIEW_ADMIN',
  ASSESSMENT_SECRET_LOOKUP: 'ASSESSMENT_SECRET_LOOKUP',

  ARTICLE_CREATE: 'ARTICLE_CREATE',
  ARTICLE_EDIT: 'ARTICLE_EDIT',
  ARTICLE_DELETE: 'ARTICLE_DELETE',
  ARTICLE_PUBLISH: 'ARTICLE_PUBLISH',
  ARTICLE_VIEW_ADMIN: 'ARTICLE_VIEW_ADMIN',

  MEDIA_UPLOAD: 'MEDIA_UPLOAD',
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.CONSULTATION_EDIT,
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
    PERMISSIONS.PARTICIPANTS_VIEW_ADMIN,
    PERMISSIONS.ASSESSMENT_SECRET_LOOKUP,

    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_EDIT,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_PUBLISH,
    PERMISSIONS.ARTICLE_VIEW_ADMIN,

    PERMISSIONS.MEDIA_UPLOAD,
  ],

  CONSULTATION_ADMIN: [
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.CONSULTATION_EDIT,
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
    PERMISSIONS.PARTICIPANTS_VIEW_ADMIN,
  ],

  CONTENT_ADMIN: [
    PERMISSIONS.ARTICLE_CREATE,
    PERMISSIONS.ARTICLE_EDIT,
    PERMISSIONS.ARTICLE_DELETE,
    PERMISSIONS.ARTICLE_PUBLISH,
    PERMISSIONS.ARTICLE_VIEW_ADMIN,
    PERMISSIONS.MEDIA_UPLOAD,
  ],

  ANALYTICS_ADMIN: [
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
  ],

  AUDITOR: [
    PERMISSIONS.CONSULTATION_VIEW_ADMIN,
    PERMISSIONS.RESULTS_VIEW_ADMIN,
    PERMISSIONS.ANALYTICS_VIEW_ADMIN,
    PERMISSIONS.PARTICIPANTS_VIEW_ADMIN,
    PERMISSIONS.ASSESSMENT_SECRET_LOOKUP,
  ],

  USER: [],
};

export function hasPermission(
  role: string | null | undefined,
  permission: Permission,
): boolean {
  if (!role) {
    return false;
  }

  return (ROLE_PERMISSIONS[role] ?? []).includes(permission);
}
